# WEEK6 DAY1- LINEAR ALGEBRA


## MATRIX
Matrix is a collection of numbers arranged or ordered in rows and columns
### SCALER :
it has no dimension and has a single element e.g [2], [a].
### VECTOR:
It is practically the simplest algebraic object, and it has one dimension, it could either be a row vector or a column vector [2 3 4].It is two or more vectors that forms a two-dimensional matrix.
### TENSOR:
Tensor is like matrice inside a matrix


## addition of matrix
for matrix A and B to be added it must be of the same dimension 

In [1]:
# import the librabries
import numpy as np

In [18]:
A = np.array([3,5,7])
B=np.array([2,4,6])

In [3]:
C = (a+b)

In [4]:
C

array([ 5,  9, 13])

In [5]:
D = (a-b)

In [6]:
D

array([1, 1, 1])

In [19]:
a+2

array([5, 7, 9])

In [11]:
# adding scaler
5+5
sc = np.array([4])
ss = np.array([6])

In [12]:
z = (sc+ss)

In [37]:
z

array([10])

# Transpose of a matrix
Transpose turns a row matrix into a column matrix and turns a column matrix into a row matrix

In [39]:
A.T

array([3, 5, 7])

In [40]:
G = np.array([[2,4,6],[3,5,7]])

In [41]:
G

array([[2, 4, 6],
       [3, 5, 7]])

In [42]:
G.T

array([[2, 3],
       [4, 5],
       [6, 7]])

In [43]:
a_ = A.reshape(1,3)

In [44]:
a_.T

array([[3],
       [5],
       [7]])

In [2]:
v = np.array([[2,3],[5,6]])

In [3]:
v

array([[2, 3],
       [5, 6]])

In [4]:
v.T

array([[2, 5],
       [3, 6]])

### multiplying a matrix (dot product)

In [13]:
# multiplying a scaler 
np.dot(sc,ss)

24

In [14]:
L = np.array([0,2,5,8])
N = np.array([20,3,4,-1])

In [15]:
np.dot(L,N)

18

#### scaler * scaler

In [16]:
np.dot(5,6)

30

#### scaler * vector

In [17]:
5*N

array([100,  15,  20,  -5])

### Matrix * Matrix
for []A to * []B the A column length must be equal to the B row length 
eg 4x5 . 5x2

In [22]:
M = np.array([[5,12,6],[-3,0,14]])
O = np.array([[2,-1],[8,0],[3,0]])

In [23]:
O

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [24]:
np.dot(M,O)

array([[124,  -5],
       [ 36,   3]])

In [26]:
H = np.array([[-12,5,-5,1,6],[6,-2,0,0,-3],[10,2,0,8,0],[9,-4,8,3,-6]])
I = np.array([[6,-1],[8,-4],[2,-2],[7,4],[-6,-9]])

In [27]:
np.dot(H,I)

array([[-71, -48],
       [ 38,  29],
       [132,  14],
       [ 95,  57]])