# WEEK5-DAY4: Feature scaling
Feature scaling is the process of transforming data into a standard scale

In [1]:
#import libraries
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
sns.set()
import statsmodels.api as sm 

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [2]:
# load data
data = pd.read_csv('1.02. Multiple linear regression.csv')

In [3]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [4]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

In [5]:
scaler = StandardScaler()

In [6]:
scaler.fit(x)

StandardScaler()

In [7]:
x_scaled= scaler.transform(x)

In [8]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [9]:
reg= LinearRegression()
reg.fit(x_scaled,y)

LinearRegression()

In [10]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [11]:
reg.intercept_

3.330238095238095

## create a summary table

In [17]:
reg_summary = pd.DataFrame([['Bias'],['SAT'],['GPA']], columns=['features'])

In [20]:
reg_summary['weights'] = reg.intercept_,reg.coef_[0], reg.coef_[1]

In [21]:
reg_summary

features   weights
0     Bias  3.330238
1      SAT  0.171814
2      GPA -0.007030

## making predictions with the standardize coefficients(weights)

In [23]:
new_data = pd.DataFrame(data=[[1700,2],[1800,1]],columns=['SAT','Rand 1,2,3'])

In [24]:
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [25]:
new_data_scaled = scaler.transform(new_data)

In [26]:
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [27]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

In [38]:
sum_table =  pd.DataFrame(data=[[1700,2],[1800,1]],columns=['SAT','Rand 1,2,3'])

In [46]:
sum_table['GPA_predictions']= reg.predict(new_data_scaled)

In [45]:
sum_table.rename(index={0:'john',1:'ray'})

SAT  Rand 1,2,3  GPA_predictions
john  1700           2         3.090514
ray   1800           1         3.264138

## what happens if we remove the the Rand 1,2,3

In [47]:
simple_data = pd.read_csv('1.01.+Simple+linear+regression.csv')

In [48]:
simple_x = data['SAT']
y= data['GPA']

In [49]:
simple_reg= LinearRegression()

In [50]:
simple_x_matrix= x_scaled[:,0].reshape(-1,1)

In [52]:
simple_reg.fit(simple_x_matrix,y)

LinearRegression()

In [54]:
simple_reg.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])